fix permission of GitHub Actions workflow.
I got some errors on GitHub Actions.

```
  ℹ️ - JUnit Report (5.10) - 143 tests run, 143 passed, 0 skipped, 0 failed.
  ℹ️ - JUnit Report (5.10) - Creating check for
  Error: ❌ Failed to create checks using the provided token. (HttpError: Resource not accessible by integration)
  Warning: ⚠️ This usually indicates insufficient permissions. More details: https://github.com/mikepenz/action-junit-report/issues/23
```

Because the default permissions have changed,
permissions must be set explicitly..